### PR TITLE
Fix ods include paths in macro, allowing for new dialects

### LINKED ISSUE #540: IRDL support for custom dialect definition
I am currently adding [IRDL support for custom dialect definition to the C API](https://github.com/llvm/llvm-project/pull/91852), and once this has landed I'd like to add it to melior as well. Ideally a macro to generate useful Rust types from IRDL definitions would be really nice, but simply allowing to register custom dialects specified in IRDL would already be sufficient.

### PR DESCRIPTION
**Pull request by edg-l**
This fixes support for the following dialects in ODS like IRDL

Fixes #540 

This pr includes #639

### CODE REVIEW

**Comment by Moxinilian** [comment]
Looks good to me for the IRDL part.

**Comment by edg-l** [comment]
@raviqqe what do you think?

**Comment by edg-l** [comment]
@raviqqe is there any blocker on this? AFAIK  the CI fails because the ods changed but that shouldn't be a bad thing in this PR, what do you think?

**Comment by raviqqe** [comment]
Hi, sorry for late reply! LGTM.

File: macro/src/dialect.rs [hunk 1]
```diff
@@ -16,13 +16,27 @@ use operation::Operation;
...
 use quote::quote;
-use std::{env, fmt::Display, str};
+use std::{env, fmt::Display, path::Path, str};
 use tblgen::{record::Record, record_keeper::RecordKeeper, TableGenParser};
 
 pub fn generate_dialect(input: DialectInput) -> Result<TokenStream, Box<dyn std::error::Error>> {
     let mut parser = TableGenParser::new();
 
     if let Some(source) = input.table_gen() {
+        let base = Path::new(env!("LLVM_INCLUDE_DIRECTORY"));
```
Comment (raviqqe) [inline macro/src/dialect.rs:26]: @edg-l Did you add this because the previous source parser was failing handling multiple `include` statements? Shouldn't we fix the `TableGenParser` instead? Or, are we just resolving their full paths?

File: macro/src/dialect.rs [hunk 2]
```diff
@@ -16,13 +16,27 @@ use operation::Operation;
...
+
+        // Here source looks like " include "somepathto.td" include "somepathto2.td" "
+        for (i, p) in source.split_ascii_whitespace().enumerate() {
```
Comment (raviqqe) [inline macro/src/dialect.rs:29]: @edg-l Doesn't this reject other inline statements in TableGen although I'm not sure how useful they are?

File: macro/src/dialect.rs (hunk 1 above)
Comment (edg-l) [reply macro/src/dialect.rs:26]: im adding their full paths, tblgen failed because it didnt find the relative include paths

File: macro/src/dialect.rs (hunk 2 above)
Comment (edg-l) [reply macro/src/dialect.rs:29]: it does, but i guessed we only add include directives here

Comment (raviqqe) [reply macro/src/dialect.rs:29]: I'm gonna make it a new option then just in case. 👍

Comment (raviqqe) [reply macro/src/dialect.rs:29]: Hmmm, actually the macro input is overcomplicated I think because the `table_gen` doesn't really make sense for the use case of MLIR as the content can't be used by the other LLVM tools, such as `mlir-tblgen`. I'm gonna make a PR to refactor them.
